name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Build with Gradle
      run: bash ./gradlew build --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/app-release-unsigned.apk

